### ISSUE TITLE
css3base

### ISSUE THREAD

**Issue by xuedaobian** [xuedaobian/blog#2]
## 盒模型 
```css
box-szing: content-box, padding-box, border-box, margin-box
```
盒子的四个组成区域相对应，每个盒子有四个边界：内容边界 Content edge、内边距边界 Padding Edge、边框边界 Border Edge、外边框边界 Margin Edge。

![box-modle](https://github.com/xuedaobian/blog/blob/master/images/box-szing.png?raw=true)

- content-box 
  是默认值。如果你设置一个元素的宽为100px，那么这个元素的内容区会有100px 宽,即content-width=100px，并且任何边框和内边距的宽度都会被增加到最后绘制出来的元素宽度中。

- border-box 告诉浏览器：你想要设置的边框和内边距的值是包含在width内的。也就是说，如果你将一个元素的width设为100px，那么这100px会包含它的border和padding，内容区的实际宽度是width减去(border + padding)的值。大多数情况下，这使得我们更容易地设定一个元素的宽高。

## flex-box
一种一维的布局模型。它给 flexbox 的子元素之间提供了强大的空间分布和对齐能力。
在父级容器上设置了 display: flex; 属性，这样就可以使用 flex-box 模型来布局。

主轴是子项目排列方向的轴，默认是水平方向，可以通过 flex-direction 属性来改变。交叉轴则是垂直于主轴。

可以设置文字的起始位置和书写方向以及对齐方式，换行方式，以及文字的垂直对齐方式。

子项目注意flex属性，它是flex-grow,flex-shrink,flex-basis三个属性的组合，flex-basis 定义了该元素的空间大小。flex-grow 管放大，flex-shrink 缩小.

bug see [👉 there](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax)

## css常用选择器及其权重比较

严格来讲，选择器的种类可以分为三种：标签名选择器、类选择器和ID选择器。而所谓的后代选择器和群组选择器只不过是对前三种选择器的扩展应用。

---
- 通配符选择器（＊）
- id选择器（\#ID）
- 类选择器（.className）
- 元素选择器(E)
- 后代选择器（Ｅ Ｆ）
- 子元素选择器(E>F)
- 相邻兄弟元素选择器(E + F)
- 群组选择器（selector1,selector2,...,selectorN）
---
**tagname < class < ID**

使用 [🌐BEM](http://getbem.com/faq/#custom-tags-for-blocks) 来解决很多无聊的问题。如样式覆盖。

查看层叠规则：[🌐CSS层叠规则](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Positioning/Understanding_z_index)

## float
float CSS属性指定一个元素应沿其容器的左侧或右侧放置，允许文本和内联元素环绕它。该元素从网页的正常流动(文档流)中移除，尽管仍然保持部分的流动性（依然在当前流中),清除浮动用clear属性。

##  块格式化上下文（Block Formatting Context, BFC）
块格式化上下文对浮动定位（参见 float）与清除浮动（参见 clear）都很重要。浮动定位和清除浮动时只会应用于同一个BFC内的元素。浮动不会影响其它BFC中元素的布局，而清除浮动只能清除同一BFC中在它前面的元素的浮动。外边距折叠（Margin collapsing）也只会发生在属于同一BFC的块级元素之间。

👉 [normal flow](https://swordair.com/css-positioning-schemes-normal-flow/)

## transition, transform,animation

在最基本的层面上，transform 移动或改变元素的外观，而 transition 使元素从一种状态平滑地逐渐变化到另一种状态,animation 定义了一组动画，可以在一个元素上运行多个动画。

```css
div {
  transition: [property] [duration] [timing-function] [delay];
  transform: [transform-list];
  animation: [animation-name] [duration] [timing-function] [delay] [iteration-count] [direction] [fill-mode] [play-state];
  @keyframes [animation-name] {
    [keyframes-selector] {
      [keyframes-declaration];
    }
  }
}
/* eg */
div {
  transition: all 1s ease-in-out;
  transform: translateX(100px);
  animation: move 1s linear infinite;
  @keyframes move {
    0% {
      transform: translateX(0px);
    }
    100% {
      transform: translateX(100px);
    }
  }
}
```
[🌐 transition & transform](https://thoughtbot.com/blog/transitions-and-transforms)
[🌐 animation](https://thoughtbot.com/blog/css-animation-for-beginners)

## 响应式布局

REFERENCE: 
- [🌐CSS响应式布局](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Responsive_Design/Using_CSS_breakpoints)
- [🌐Responsive Web Design - What It Is And How To Use It](https://www.smashingmagazine.com/2011/01/guidelines-for-responsive-web-design/#the-concept-of-responsive-web-design)
